plugin: amazon.aws.aws_ec2
regions:
  - eu-west-1

filters:
  tag:Name: "ec2_techn-*" 

# keyed_groups:
#   - key: tags.Name
#     prefix: "tag"

hostnames:
  - tag:Name  
compose:
  ansible_host: instance_id 
  ansible_connection: aws_ssm
  ansible_aws_ssm_region: eu-west-1