name: App deployment CI/CD Pipeline

on:
  push:
    branches:
      - IAC
    paths:
      - 'App/**'
      - '.github/workflows/app_deploy.yaml'
  pull_request:
    branches:
      - IAC
    paths:
      - '.github/workflows/app_deploy.yaml'
      - 'App/**'
  workflow_dispatch: 

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read

jobs:
  install_dependencies:
    name: install App dependencies
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: App
    steps:

    - name: checkout code from repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
      with:
        role-to-assume: ${{ secrets.EC2_GH_ROLE }}
        role-session-name: ghrolesession
        aws-region: ${{ secrets.REGION }}

    - name: Zip App folder
      run: |
        zip -r app.zip .

    - name: Upload app.zip to S3
      run: |
        aws s3 cp app.zip s3://technn-deployment-bucket/app.zip

    - name: Install Ansible dynamic inventory dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install "boto3" "botocore" "ansible==11.0.0"
        ansible --version

    - name: Install Ansible AWS collection
      run: |
        ansible-galaxy collection install amazon.aws:>=7.0.0 --force
        ansible-galaxy collection list


    - name: Run app_dependencies playbook
      env:
        ANSIBLE_USER: ubuntu
        ANSIBLE_HOST_KEY_CHECKING: False
        ANSIBLE_INVENTORY_ENABLED: amazon.aws.aws_ec2,ini,yaml
      run: |
        ansible-inventory -i ansible/app_deploy.aws_ec2.yaml --graph
        ansible-doc -t connection amazon.aws.aws_ssm

        ansible-playbook -i ../ansible/app_deploy.aws_ec2.yaml ../ansible/app_dependencies.yaml -u ubuntu -e "ansible_connection=amazon.aws.aws_ssm"
  
  deploy:

    name: deploy app
    runs-on: ubuntu-24.04
    needs: install_dependencies
    steps:

    - name: checkout code from repo
      uses: actions/checkout@v4

    - name: Install Ansible dynamic inventory dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install "boto3" "botocore" "ansible==11.0.0"
        ansible --version

    - name: Install Ansible AWS collection
      run: |
        ansible-galaxy collection install amazon.aws:>=7.0.0 --force
        ansible-galaxy collection list 


    - name: Run app_deploy playbook
      env:
        ANSIBLE_USER: ubuntu
        ANSIBLE_HOST_KEY_CHECKING: False
        ANSIBLE_INVENTORY_ENABLED: amazon.aws.aws_ec2,ini,yaml
      run: |
        ansible-playbook -i ansible/app_deploy.aws_ec2.yaml ansible/app_deploy.yaml -u ubuntu -e "ansible_connection=amazon.aws.aws_ssm"

    - name: Delete app.zip from S3
      run: |
        aws s3 rm s3://technn-deployment-bucket/app.zip






      